apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-deployment-tutorial
  
spec:
  replicas: 1
  selector:
    matchlabels:
      app: gcp-deployment-tutorial
  template:
    metadata:
      labels:
        app: gcp-deployment-tutorial
        
    spec:
      containers: 
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always